version: '3.5'
services:

  hadoop:
    build: ./hadoop
    restart: always
    image: rhadoop-hadoop
    container_name: rhadoop
    hostname: rhadoop
    ports:
      - "9000:9000"     # Hadoop
      - "50070:50070"   # Hadoop UI
      - "50075:50075"
      - "8088:8088"
    networks:
      rconnect_network:
    volumes:
      - hadoopdata:/opt/hadoop-data

  hive:
    build: ./hive
    restart: always
    image: rhadoop-hive
    container_name: rhive
    hostname: rhive
    ports:
      - "10000:10000"
      - "9999:9999"  ##Hive UI
      - "9083:9083"  ## Hive Metastore
    networks:
      rconnect_network:
    depends_on:
      - hadoop

  master:
    build: ./spark
    image: rspark-master
    container_name: rspark-master
    hostname: rspark-master
    environment:
      - "SPARK_LOCAL_IP=rspark-master"
    ports:
      - "7077:7077"
      - "8080:8080"     # Master Web UI
      - "4040:4040"
      - "4041:4041"
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    networks:
      rconnect_network:

  worker1:
    image: rspark-master
    container_name: rspark-worker-1
    hostname: rspark-worker-1
    ports:
      - "8081:8081"     # Worker Web UI
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    environment:
      SPARK_LOCAL_IP: rspark-worker-1
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 4g
    networks:
      rconnect_network:
    depends_on:
      - master

  worker2:
    image: rspark-master
    container_name: rspark-worker-2
    hostname: rspark-worker-2
    ports:
      - "8082:8081"     # Worker Web UI
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    environment:
      SPARK_LOCAL_IP: rspark-worker-2
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 4g
    networks:
      rconnect_network:
    depends_on:
      - master
volumes:
  hadoopdata:

networks:
  rconnect_network:
    name: rconnect
    driver: bridge
