---
title: "RStudio"
author: "Jim Harner"
date: "5/7/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

RStudio is an integrated development environment (IDE) that runs on all major platforms. We are running RStudio Server.

Once you log into RStudio Server you will see four panels, which can be customized by choosing `Global Options ...` from the `Tools` menu. You can then rearrange what appears in the panels to suit your needs. I would recommend that you leave `Source` in the upper left and move the `Console` to the lower right. It is useful to have "Plots, Packages, Help, and Viewer" in the upper right panel so that output is beside the source code.

You can use R interactively from the `Console`, but most of your work will consist of developing source files. For the most part you will be creating R Markdown files, but in some cases you will develop R scripts. New files can be created by selecting `New File` from the `File` menu and then selecting the type of file desired, typically either R Markdown or R Script.

First you will need to get content into your home directory. Select `Shell...` from the `Tools` menu. To get oriented, type the following into the shell.
```{bash}
pwd
cd $HOME
ls
```
`pwd` prints the working directory. We then change directory (`cd`) to the home directory using the `HOME` environmental variable, also denoted by `~`. You should now be in the directory `/home/yourloginname`. Unless you have previously added content, the directory is empty (except perhaps an `R` directory) as given by `ls`, which lists the contents of your working (in this case home) directory.

Next let's make a directory for this class:
```{bash}
# Make the NISS directory only once
# mkdir NISS
cd NISS
ls -al
```
`mkdir` makes a directory, in this case `NISS`. You are still in your home directory and you can list its contents with `ls -al` or `ls -a -l` if you prefer. Note that `ls`  has options where `-a` lists all files and directories, including hidden files beginning with `.` and `-l` specifies long format (`l`), which gives the permissions and other information about the owner, etc. For `NISS` you will see `drwxr-xr-x`. The first `d` indicated `NISS` is a directory. Then we have permissions (file modes) in three sequences of three each:

* The first `rwx` indicates you (the owner) have read, write, and execute permissions;  
* The second `r-x` indicate your group has read and execute permissions, but not write.  
* The third `r-x` indicates all users have read and execute permissions, but not write.  

These permissions are also denoted by `755`, where $7 = 2^2 + 2^1 + 2^0$ and the exponent is the position in the sequence `rwx` from right to left beginning at 0. In a similar vein, `r-x` can be represented as $5 = 2^2 + 0 + 2^0$. The default when you create a directory is `755`. Execute permission is important for a directory since otherwise you cannot `cd` to the directory.

Note that if you want privacy you should use `700` for permissions. Let's make a temporary directory and then change its permissions.  
```
mkdir temp
ls -al
chmod 700 temp
ls -al
rmdir temp
```
We use `chmod` (change mode) to change the permissions of `temp` from the default `755` to `700`. You can check this out in each case by `ls -al`. We then remove the directory, which must be empty, by `rmdir`.

Linux has a large number of built-in commands which you should gradually learn. Extensive information is given by the `man` or manual pages for each command. For example:
```
man chmod
```
Most commands have many options, but usually you can get by with a few. Often the output from `man` is overwhelming and thus you might do better by googling the command.

In the next section we will create a project called `Modules`, which is a subdirectory of `~/NISS`.
